export const ADD_USER_TO_SOCKET = "ADD_USER_TO_SOCKET";
export const REMOVE_USER_FROM_SOCKET = "REMOVE_USER_FROM_SOCKET";
export const ADD_GAME_TO_SOCKET = "ADD_GAME_TO_SOCKET";
export const REMOVE_GAME_FROM_SOCKET = "REMOVE_GAME_FROM_SOCKET";
